### ISSUE TITLE
on gcp, health checks can't be deleted if they're being used by a target pool

### ISSUE THREAD

**Issue by cwlbraa** [genevieve/leftovers#19]
```
[Http Health Check: k8s-fbf9289ab476c911-node] Delete: Operation error: The http_health_check resource 'projects/cf-infra/global/httpHealthChecks/k8s-fbf9289ab476c911-node' is already being used by 'projects/cf-infra/regions/us-east1/targetPools/ab942aa3d31f811e8936a42010a00100'
```

**Comment by genevieve** [comment]
Were you prompted to delete that target pool? 

Did both the http health check and target pool have a name with the filter?

**Comment by cwlbraa** [comment]
we weren't prompted and the names didn't match.

**Comment by genevieve** [comment]
We delete health checks after target pools but if the target pool hasn't been deleted, we can't delete the health check. The problem with asking if a health check is in use is that you would have to describe the health check twice - one request in order to get a list of health checks that can be deleted, and then a second time to check before deleting it. You can't skip it in the first filtering because otherwise you would have to run leftovers more than once to delete resources in an environment (like in ci). 

The weird thing is - why does the target pool not have an identifier that matches the filter if the health check does? How were these resources created? We should add tags or more details when we create them.

**Comment by cwlbraa** [comment]
the load balancers were created via a kubernetes cloud-provider.

**Comment by genevieve** [comment]
If the target pools don't contain any identifier with the environment name (tags or whatnot), I suppose we could verify while deleting a health check if there are target pools to delete beforehand if the api returns those details.
