### ISSUE TITLE
Filter resources by status

### ISSUE THREAD

**Issue by dtimm** [genevieve/leftovers#26]
It would be helpful to have the ability to filter resources by Running/Stopped/Suspended status.

**Comment by genevieve** [comment]
Do you mean so you could terminate resources that are running but not those that are Stopped or Suspended? Did you see an error where leftovers was trying to shut down an already stopped resource? I can add functionality to skip resources that are already being shut down so that the user doesn't need to know that detail.

**Comment by dtimm** [comment]
In the case that brought this up, we specifically want to wipe suspended VMs and unattached persistent disks.

**Comment by genevieve** [comment]
There are a lot of resources across all the IaaSes that have no status, so should we skip those if a status flag is passed? Should the value of the status flag need to match precisely with the IaaS resource's specification for that value?

**Comment by genevieve** [comment]
Going to close this for now since trying to filter by the various iaas-specific/resource-specific statuses will be rather complex and would require the user to know what terminology is used for each status. Instead, the user can go with being prompted and determine the status if need be!
