### ISSUE TITLE
Confusing output running `leftovers --dry-run` when there are elastic IPs on a managed NAT gateway

### ISSUE THREAD

**Issue by nmahoney-pivotal** [genevieve/leftovers#34]
`aws.Addresses.List` will just add any elastic IP that isn't attached to a VM to the list regardless of filter. This produces confusing results when running `leftovers --dry-run` on an AWS region that has unattached elastic IPs; regardless of where they came from, it lists all EIPs. This includes EIPs that are attached to a managed NAT gateway (or other non-instance resource) *in another VPC*.

**Comment by genevieve** [comment]
The thing with addresses is that they oftentimes don't have tagging that we can filter on. Oftentimes, they get orphaned from an instance and then there is no way to collect them because they have no associated objects with filterable tags themselves. For this resource in particular, we don't remove them  from the potential list because they might actually be related, and we don't remove them just because they might be in use, because the listing happens before deleting - so an instance that you will approve to delete is still technically using the address at the time we prompt you. Instead, we allow you to try and delete that address but if you don't also agree to delete it's bound instance with `leftovers`, then the aws api will return the error. Otherwise, users would always have to run `leftovers` twice to delete an environment. The first time around they would catch the instance, the second time they would catch the address (if that address somehow retained something we could filter on.)
