### ISSUE TITLE
IAM Server Certificate not being deleted on AWS when still seen as In Use by recently deleted LB

### ISSUE THREAD

**Issue by rszumlakowski** [genevieve/leftovers#42]
I'm using Pivotal's `terraforming-aws` to create some infrastructure on AWS and I'm trying to use `leftovers` v0.34.0 to clean it up.  Unfortunately, the "IAM Server Certificate" is not being deleted.  I assume it's because the load balancer is taking too long to deleted.

```
[IAM Server Certificate: robtestenv7-20180725144713463300000001] Deleting...
[IAM Server Certificate: robtestenv7-20180725144713463300000001] Delete: DeleteConflict: Certificate: ASCAJ2HG4ZIKYRFPOFBOG is currently in use by arn:aws:elasticloadbalancing:us-east-1:975153460263:loadbalancer/robtestenv7-web-elb. Please remove it first before deleting it from IAM.
	status code: 409, request id: 06b19273-901a-11e8-ba16-3f3e4f345a73
```

If I run `leftovers` again then the IAM Server Certificate is deleted successfully.

I'm concerned because the first run of `leftovers` prints an error to the log but exits with a status code of 0.  It will be hard to run `leftovers` programmatically since it's not returning an error status.

So, I have created this issue to report two problems:

1. IAM Server Certificates not being deleted successfully on AWS.
2. The exit status needs to be non-zero if the above error occurs.

Please refer to the attached log file.

[leftovers_error.log](https://github.com/genevieve/leftovers/files/2228394/leftovers_error.log)

**Comment by genevieve** [comment]
Hey Robert!

1. Because it's eventually consistent, we can retry deleting the iam server certificate for a longer period of time.

2. This is definitely something to fix. Should there be a `--fast-fail` flag? The reason why `leftovers` doesn't exit 1 when a single resource fails is because of issues like this where it's about eventual consistency, and the resource that's orphaned doesn't cause name collisions (because there's a guid in there.) There are also some cases where APIs return failures for deletion when the resource was already deleted (but that's the goal so we don't want it to be seen as a failure.) Alternatively to the previous question, should the default be to to exit 1 and the feature flag is to `--just-keep-going`?

**Comment by rszumlakowski** [comment]
Thanks for getting back to me so quickly, @genevieve !

I'm not sure if I'd ask you to introduce breaking changes to the `leftovers` interface.  Maybe it makes more sense to implement a `--fast-fail` rather than a `--just-keep-going`?

I did see at least one time today where the IAM Server Certificate was deleted successfully the first time so I think retrying the deletion of the IAM Server Certificate would help a lot.

**Comment by genevieve** [comment]
I've added some retries to the command. In the terraform-provider-aws code, they retry for nearly 15 minutes so I may need to extend the # of retries/time spent retrying if you continue to see this!

**Comment by rszumlakowski** [comment]
Thank you, Gen!  I'll let you know if we still see this issue.
