### ISSUE TITLE
Different exit codes for fatal and nonfatal errors

### ISSUE THREAD

**Issue by rszumlakowski** [genevieve/leftovers#60]
We'd like to use `leftovers` to clean up environments that we pave.  Sometimes, due to race conditions or other things `leftovers` is not able to delete everything each time it runs.  In those cases it's easy to run `leftovers` several times until it manages to delete everything.  Sometimes, however, `leftovers` might exit for reasons that attempting any retries won't help (e.g.: bad credentials or configuration).

To help support this scenario it would be helpful if leftovers returned several kinds of errors codes:
 * Fatal errors where retries should not be attempted (e.g.: exit code 2)
 * Non-fatal errors where retries should be attempted (e.g.: exit code 1)
 * Successful run (e.g.: exit code 0)

**Comment by genevieve** [comment]
Hey! I've thought about this a lot, and I think I would prefer to build retry logic into leftovers on a resource-by-resource basis instead of having users build that retry logic around leftovers in their own tooling. I'm going to close this issue and open new issues as we discover resources that require retrying.
