### ISSUE TITLE
AWS Volumes and addresses are not filtered

### ISSUE THREAD

**Issue by acrmp** [genevieve/leftovers#63]
It seems that the filter provided with `--filter` is not applied to EBS volumes and EIP's for AWS (by design).

https://github.com/genevieve/leftovers/blob/8c717a627e9a66016dde8df78180ce16208db38e/aws/ec2/volumes.go#L28
https://github.com/genevieve/leftovers/blob/8c717a627e9a66016dde8df78180ce16208db38e/aws/ec2/addresses.go#L27

Is leftovers safe to run with a filter periodically in an account where there may be multiple environments? It seems that volumes that have been created but not yet attached or that are being re-attached to a new node could be seen by leftovers and destroyed?

Would it be better for `leftovers` to assume that whatever is creating the resources is correctly tagging them?

**Comment by genevieve** [comment]
That is possible with an account that has multiple environments. The issue was the many volumes/addresses not being tagged and then being orphaned and leftovers being unable to ever delete them.

I can go back to using the `Tags` field on these and if users report it being hard to clean these two, I could probably try to implement a `--force` flag?

What do you think?

**Comment by genevieve** [comment]
Resolved via DM: these resources will filter using their tags. We are assuming that they are correctly tagged instead of trying to be too helpful and potentially deleting too aggressively.

**Comment by genevieve** [comment]
https://github.com/pivotal-cf/terraforming-aws/pull/65

**Comment by genevieve** [comment]
Should be in the next release! Thanks Andrew for your help!
