### ISSUE TITLE
`leftovers` isn't finding VPCs on AWS

### ISSUE THREAD

**Issue by nmahoney-pivotal** [genevieve/leftovers#72]
leftovers output:
![screen shot 2019-01-15 at 5 03 34 pm](https://user-images.githubusercontent.com/12817808/51219905-d31e4880-18e7-11e9-8f78-38630fdcbfc0.png)

VPC section on AWS console:
![screen shot 2019-01-15 at 5 04 08 pm](https://user-images.githubusercontent.com/12817808/51219908-d4e80c00-18e7-11e9-80b3-c868b70ff9f1.png)

As you can see above, the VPCs exist that match the filter, but leftovers isn't finding them ☹️ .

**Comment by genevieve** [comment]
That’s weird! What version of leftovers is this? The vpc code checks if the vpc id (name) contains the filter and also checks that the vpc is not the default, but otherwise, it returns it as deletable. The vpc and these other resources are also in the same region? 

The vpc code hasn’t changed in a while so I’m really curious why it would be skipping or not seeing these vpcs.

**Comment by genevieve** [comment]
I wonder if this is an old version of leftovers because the formatting of the output is really unusual.

**Comment by genevieve** [comment]
Update

The vpcs were not showing up because they belonged to a different aws region than the one passed to `leftovers`. The iam resources are showing up because iam resources do not belong to any region, they are globally available resources.

**Comment by nmahoney-pivotal** [comment]
User error :)

Thanks!
