### ISSUE TITLE
AWS - VPC deletion fails because of dependencies but deletes just fine in the AWS console

### ISSUE THREAD

**Issue by nmahoney-pivotal** [genevieve/leftovers#86]
![Screen Shot 2019-06-07 at 10 02 25 AM](https://user-images.githubusercontent.com/12817808/59120936-9214e800-890b-11e9-9129-12e15cfa3505.png)

Deleting this VPC worked just fine in the AWS console using the same account.

**Comment by genevieve** [comment]
Hey Nick!

QQs:
- Did you try running leftovers more than once?
- Were there possibly any dependencies that you had deleted (like a vm in that vpc) that could have taken a while to be truly marked as "deleted" by aws? Occasionally, resources are still considered dependencies because the iaas can take a while to consider them deleted. This is more of a problem when you deleted something in the aws console like the vm, then tried to delete the network with leftovers because if you try to delete the vm with leftovers first -> leftovers will wait until the vm is truly marked as gone before trying to delete the vpc vs if you try with the console first, the status of the vm will be "deleting" and leftovers won't try to delete it itself and then proceed to the vpc.

**Comment by nmahoney-pivotal** [comment]
We ran leftovers thrice in the pipeline ([this build](https://infra.ci.cf-app.com/teams/main/pipelines/bosh-bootloader/jobs/aws-acceptance-tests-bump-deployments/builds/150) and the previous two), and once manually. Then we deleted in the console right after that and it worked. We hadn't done anything manual, and I think the pipeline just interacts with AWS through bbl and leftovers. I don't think there was any manual deletion.

**Comment by nmahoney-pivotal** [comment]
P.S. Hi Gen!

**Comment by genevieve** [comment]
Hi Nick!!!

Alright, what I'm gathering:
1. The first failure is in build #147 where bosh fails to delete the jumpbox. [Here](https://infra.ci.cf-app.com/teams/main/pipelines/bosh-bootloader/jobs/aws-acceptance-tests-bump-deployments/builds/147#L5cd34ba3:986)
2. The next failure is in build #148 where leftovers [reports that it deleted the jumpbox](https://infra.ci.cf-app.com/teams/main/pipelines/bosh-bootloader/jobs/aws-acceptance-tests-bump-deployments/builds/148#L5cd34bdd:80), but then proceeds to [fail trying to delete the vpc](https://infra.ci.cf-app.com/teams/main/pipelines/bosh-bootloader/jobs/aws-acceptance-tests-bump-deployments/builds/148#L5cd34bdd:97)
3. The next failure is in build #149, about 40 minutes later, and proceeds to fail to delete the vpc.
4. The next failure is in build #150, about 30 minutes later, and proceeds to fail to delete the vpc.
5. When you delete the vpc in the console successfully, the next build passes.

Since this is the first time this is happening, I'm wondering what are conditions that make this situation unique. Are there perhaps any new resource types that we are creating in the bbl aws terraform templates? The aws api is returning a 400 saying there are dependencies, but I know that from the console, you are allowed to delete it regardless _given_ those dependencies are certain types.

Maybe an action we can take is: can the aws api give us a better error message about what dependencies exist? 

Alternatively, we could narrow down to what dependencies can be deleted by deleting the vpc in the console _that you can't_ delete by deleting the vpc by using the api.

**Comment by rowanjacobs** [comment]
Looks like this is [still happening](https://infra.ci.cf-app.com/teams/main/pipelines/bosh-bootloader/jobs/aws-acceptance-tests-bump-deployments/builds/177). Can you post the output of `aws ec2 describe-subnets --filters "Name=vpc-id,Values=vpc-0aa226bc62915c540"`? @nmahoney-pivotal

**Comment by genevieve** [comment]
It's interesting that it always happens after a bosh failure like [this](https://pivotal.slack.com/archives/DHRUW8W4D/p1559919892006500)...

**Comment by rowanjacobs** [comment]
That link doesn't work! 😔 But I think I can see the one you're referring to from earlier concourse logs.

This is beginning to remind me of the early bbl on OpenStack failures where incompletely creating a VM would result in a "port" (OpenStack static private IP allocation) being left behind without a VM attached to it. I wonder if there was a recent AWS CPI change that created a similar kind of shadow resource that doesn't get cleaned up by leftovers, and if so what that would be.

**Comment by nmahoney-pivotal** [comment]
@rowanjacobs I thought I sent this before... I guess not. Here's that output:
```
$ aws ec2 describe-subnets --filters "Name=vpc-id,Values=vpc-0aa226bc62915c540"
{
    "Subnets": []
}
```

**Comment by genevieve** [comment]
Closing this issue until (if) we see it again and can access the environment to debug.

**Comment by genevieve** [comment]
It appears that occasionally there are load-balancers deployed to a network that do not contain the full filtering string. For instance, bbl sometimes crops the environment name when creating resources to fit the length limit when needed. https://github.com/cloudfoundry/bosh-bootloader/blob/a1f38c83bd02f71bab4dea46ce4cae86336969ff/terraform/aws/templates/concourse_lb.tf#L56

Leftovers doesn't return them in the list because they do not contain the _full_ filter string like `bump-deployments-aws-concourse` since the load balancer might be created with just `bump-deplo` as prefix.
